import "reflect-metadata";
import type { Metadata } from "next";
import "../globals.css";
import { redirect } from "next/navigation";
import Nav from "../components/Nav";
import { getAuthUser } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { loginUrl, user } = await getAuthUser();
  if (!user) return redirect(loginUrl);
  return (
    <html lang="en" data-theme="light">
      <body>
        <Nav />
        <a className="btn btn-sm btn-outline m-3" href="/api/logout">
          Logout
        </a>
        {/* <pre>{JSON.stringify(user, null, 2)}</pre> */}
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
